# Generated by Django 4.2.2 on 2023-06-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('category', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
    ]
